FROM --platform=linux/amd64 node:18-slim

WORKDIR /usr/src/app

COPY . .

RUN yarn install

RUN yarn global add prisma
RUN yarn add @prisma/client
RUN apt-get update && apt install -y openssl
RUN yarn add bcrypt
RUN yarn add jsonwebtoken
RUN yarn add cors
RUN prisma generate

EXPOSE 3344

CMD [ "yarn", "dev" ]